In [6]:
import pandas as pd

In [7]:
caminho_arquivo = r'C:\Users\claus_katzer\Downloads\clientes_compra_misterio.xlsx'
df_compras = pd.read_excel(caminho_arquivo)

In [8]:
mapeamento_compras_anteriores = {'Sim':1,'NÃ£o':0}

In [9]:
df_compras['compras_anteriores'] = df_compras['compras_anteriores'].map(mapeamento_compras_anteriores)

In [10]:
df_compras

    tempo_gasto_site  numero_itens_visualizados  compras_anteriores
0                 10                          5                   0
1                 15                          7                   1
2                 20                          8                   1
3                  5                          3                   0
4                 25                         10                   1
5                 30                         12                   1
6                  8                          4                   0
7                 12                          6                   1
8                 18                          9                   1
9                  7                          3                   0
10                22                         11                   1
11                28                         13                   1
12                 6                          2                   0
13                14                          7                   1
14                16                          8                   1
15                 9                          4                   0
16                24                         10                   1
17                32                         14                   1